<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>RaisedGardenBeds</RootNamespace>
		<Version>1.1.0</Version>
		<TargetFramework>net6.0</TargetFramework>
		<Platforms>AnyCPU</Platforms>
		<PlatformTarget>AnyCPU</PlatformTarget>
		<EnableHarmony>true</EnableHarmony>
	</PropertyGroup>

	<PropertyGroup>
		<LangVersion>latest</LangVersion>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>6.0</AnalysisLevel>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.3.1" />
	</ItemGroup>

	<ItemGroup>
		<Reference Include="Newtonsoft.Json" HintPath="$(GamePath)/smapi-internal/Newtonsoft.Json.dll">
			<Private>false</Private>
		</Reference>
		<Reference Include="SpaceCore">
			<HintPath>$(GamePath)\Mods\SpaceCore\SpaceCore.dll</HintPath>
			<Private>false</Private>
		</Reference>
	</ItemGroup>

	<ProjectExtensions>
		<VisualStudio>
			<UserProperties manifest_1json__JsonSchema="https://smapi.io/schemas/manifest.json" />
		</VisualStudio>
	</ProjectExtensions>

</Project>